# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "xplico"
    config.vm.network "forwarded_port", guest: 9876, host: 9876
    config.vm.network "forwarded_port", guest: 30001, host: 30001

#    config.vm.provider :virtualbox do |vb|
#        vb.gui = true
#        vb.customize ["modifyvm", :id, "--memory", "1024"]
#    end
end
