# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "freeradius"

#    config.vm.provider :virtualbox do |vb|
#        vb.gui = true
#        vb.customize ["modifyvm", :id, "--memory", "1024"]
#    end
end
